/*
 * Test class for CreateRequestForChangeController apex class
*/
@isTest
public class CreateRequestForChangeControllerTest {
	
    @isTest
    public static void testPageInitMethods() {
  //  	Request_For_Change__c testRFCRelatedSCA = PGITestUtilities.createRFC(false);
  //      testRFCRelatedSCA.Status__c = 'Approved';
  //      testRFCRelatedSCA.RecordTypeId = PGITestUtilities.RFCStandardRT;
  //      testRFCRelatedSCA.Schedule_Start_Day__c = System.Today();
  //      testRFCRelatedSCA.Schedule_Repeat_Frequency__c = 'Daily';
  //      insert testRFCRelatedSCA;
        
  //      Request_For_Change__c testRecord = PGITestUtilities.createRFC(false);
  //      testRecord.Related_SCA__c = testRFCRelatedSCA.Id;
  //      testRecord.Schedule_Start_Day__c = System.Today();
  //      testRecord.Schedule_Repeat_Frequency__c = 'Daily';
  //      insert testRecord;

  //      RFC_Risk_Assessment__c testRiskAssessment = new RFC_Risk_Assessment__c(Request_For_Change__c = testRecord.Id);
  //      insert testRiskAssessment;
  //      RFCImpact__c testRFCImpact = new RFCImpact__c(RequestForChange__c = testRecord.Id);
  //      insert testRFCImpact;

  //      Test.startTest();

  //   	PageReference pageRef = Page.CreateRequestForChange;
  //      Test.setCurrentPage(pageRef);
  //   	ApexPages.StandardController sc = new ApexPages.StandardController(testRecord);
  //   	CreateRequestForChangeController controller = new CreateRequestForChangeController(sc);
		//Boolean hasBeenPickedUp = controller.hasBeenPickedUp;
  //      Boolean hasSCASelect = controller.hasSCASelected;
  //      List<LayoutDescriberHelper.LayoutSection> testLayoutSectionsGetSet = controller.layoutSections;
  //      List<LayoutDescriberHelper.AssignmentModel> testAssignmentSectionsGetSet = controller.assignmentSections;
  //      System.assert(controller.createFromScratch() == null);
  //      System.assert(!controller.promptForRCA);
  //      System.assert(controller.prSelectRelatedSCA() == null);
  //      System.assertEquals(controller.scheduleRepeatFrequency.isEmpty(), false);
  //      // populate frequency and assert no errors
  //      controller.selectedScheduleRepeatFrequency = new String[]{'Daily'};
  //      System.assert(controller.createRFC() != null);
  //      System.assert(!controller.relatedSCAs.isEmpty());

  //      Test.stopTest();
    }


}