/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_bizible2_Bizible_Attributiona38Test
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_bizible2_Bizible_Attributa38Trigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new bizible2__Bizible_Attribution_Touchpoint__c());
    }
}