@isTest
public class Test_PopulateParentClientonConferences{
    //static testMethod void validateparentclient(){
    
    //    PGi_Entity__c ent = new PGi_Entity__c(name='ent1000');
    //    PGi_Company__c comp = new PGi_Company__c(name='comp1000',PGi_Entity__c=ent.id);
    //    PGi_Client__c cli1 = new PGi_Client__c(name='cli1000',PGi_Company__c=comp.id);
    //    PGi_Client__c cli2 = new PGi_Client__c(name='cli1001',PGi_Company__c=comp.id);
    //    PGi_Client__c cli3 = new PGi_Client__c(name='cli1001',PGi_Company__c=comp.id);
        
    //    insert ent;
    //    insert comp;
    //    insert cli1;
    //    insert cli2;
    //    insert cli3;
            
    //    Test.startTest();
    //        PGi_Conference__c conf1 = new PGi_Conference__c(name = 'conf1000',Client_ID__c = 'cli10000'); 
    //        PGi_Conference__c conf2 = new PGi_Conference__c(name = 'conf1001',Client_ID__c = 'cli1000');
    //        PGi_Conference__c conf3 = new PGi_Conference__c(name = 'conf1002',Client_ID__c = 'cli1001');
    //        insert conf1;
    //        insert conf2;
    //        insert conf3;
    //        PGi_Conference__c conf100 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1000'];
    //        PGi_Conference__c conf101 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1001'];
    //        PGi_Conference__c conf102 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1002'];
           
    //        system.assertequals(conf100.PGi_Client__c,NULL);
    //        system.assertequals(conf101.PGi_Client__c,cli1.id);
    //        system.assertequals(conf102.PGi_Client__c,NULL);
            
    //    Test.stopTest();
    //}
}